# Generated by Django 3.2.14 on 2022-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppg_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='player',
            name='predictedppg',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.CharField(max_length=5),
        ),
    ]
