# Generated by Django 3.2.14 on 2022-08-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppg_predictor', '0002_auto_20220816_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='predictedppg',
            field=models.FloatField(),
        ),
    ]
