<<<<<<< HEAD
# Generated by Django 3.2.14 on 2022-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppg_predictor', '0003_auto_20220816_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ppg',
            new_name='ppg2022',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='draftPos',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='mpg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='salary',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='years',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 3.2.14 on 2022-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppg_predictor', '0003_auto_20220816_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ppg',
            new_name='ppg2022',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='draftPos',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='mpg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='salary',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='years',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
>>>>>>> 39906e396b1bd00268ab3a1262cc3050faa24ec3
