# Generated by Django 4.1 on 2022-08-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0005_team_player_currentteam"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="potential",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="ppg_predictor.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="ppg_predictor.league",
            ),
        ),
    ]
