# Generated by Django 4.1 on 2022-08-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0006_league_player_potential_player_team_team_league"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="currentteam",),
    ]
