# Generated by Django 4.1 on 2022-08-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0007_remove_player_currentteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="leaguename",
            field=models.TextField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
