# Generated by Django 4.1 on 2022-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0011_alter_team_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="user",),
    ]
