# Generated by Django 4.1 on 2022-08-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0012_remove_team_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="league", name="season",),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=4)),
                (
                    "league",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="ppg_predictor.league",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="ppg_predictor.season",
            ),
        ),
    ]
