# Generated by Django 4.1 on 2022-08-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0013_remove_league_season_season_team_season"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="league",),
    ]
