# Generated by Django 4.1 on 2022-08-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0015_league_user_team_user_alter_league_leaguename"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="season",),
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="ppg_predictor.league",
            ),
        ),
    ]
