# Generated by Django 4.1 on 2022-08-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppg_predictor", "0016_remove_team_season_team_league"),
    ]

    operations = [
        migrations.RemoveField(model_name="league", name="user",),
        migrations.RemoveField(model_name="team", name="user",),
    ]
